# Generated by Django 5.0.3 on 2024-04-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='designer_name',
            field=models.CharField(default='Default Designer', max_length=20),
        ),
    ]
